defaults:
  - exp: train_odesign_base_prot_flex
  - hydra: default
  - _self_

data_root_dir: ./data
ckpt_root_dir: ./ckpt

exp:
  exp_name: protein_binding_protein_design
  infer_model_name: odesign_base_prot_flex
  design_modality: protein
  input_json_path: ./examples/protein_design/prot_binding_prot/odesign_input.json
  num_workers: 4
  use_msa: false
  seeds: [42, 101]
  invfold_topk: 1 # number of designed sequences per backbone structure
  invfold_temp: 1.0
  invfold_use_beam: True
  model:
    sample_diffusion:
      N_sample: 5